import { isRussianSource } from '../services/language.js';

export const DEFAULT_HTML_SELECTORS = {
  item: 'article, .post, .news-item, .card, .item, .list-item',
  title: 'h1, h2, h3, .title, .news-title, a',
  link: 'a',
  description: 'p, .summary, .lead, .excerpt, .announce',
  image: 'img',
  date: 'time, .date, .published',
};

export const TOPICS = [
  { slug: 'it', name: 'IT / Разработка', icon: 'Cpu', description: 'Разработка, инфраструктура и IT-индустрия.' },
  { slug: 'electronics', name: 'Электроника / Гаджеты', icon: 'Smartphone', description: 'Обзоры техники, смартфонов и железа.' },
  { slug: 'cinema', name: 'Кино / Сериалы', icon: 'Film', description: 'Премьеры, показы и киноновости.' },
  { slug: 'games', name: 'Игры', icon: 'Gamepad2', description: 'Игровые новости, обзоры и индустрия.' },
  { slug: 'sport', name: 'Спорт', icon: 'Trophy', description: 'Матчи, турниры и спортивные новости.' },
  { slug: 'finance', name: 'Финансы / Экономика', icon: 'LineChart', description: 'Рынки, банки и экономическая повестка.' },
  { slug: 'auto', name: 'Авто', icon: 'Car', description: 'Автомобили, тесты и рынок.' },
  { slug: 'music', name: 'Музыка', icon: 'Music2', description: 'Концерты, релизы и музыкальные новости.' },
  { slug: 'art', name: 'Культура / Искусство / Выставки', icon: 'Palette', description: 'Выставки, галереи и культурные события.' },
  { slug: 'health', name: 'Здоровье / Медицина', icon: 'HeartPulse', description: 'Медицина, исследования и здоровье.' },
  { slug: 'science', name: 'Наука', icon: 'FlaskConical', description: 'Исследования, открытия и научные новости.' },
  { slug: 'realty', name: 'Недвижимость', icon: 'Home', description: 'Рынок жилья, стройка и аналитика.' },
  { slug: 'travel', name: 'Путешествия / Туризм', icon: 'Plane', description: 'Маршруты, авиа и туристические новости.' },
  { slug: 'fashion', name: 'Мода / Красота', icon: 'Shirt', description: 'Мода, стиль и beauty-индустрия.' },
  { slug: 'crypto', name: 'Крипто / Web3', icon: 'Coins', description: 'Криптовалюты, блокчейн и Web3.' },
  { slug: 'politics', name: 'Политика / Общество', icon: 'Newspaper', description: 'Политика, общество и главные новости.' },
  { slug: 'food', name: 'Еда / Рестораны', icon: 'UtensilsCrossed', description: 'Рестораны, рецепты и гастрособытия.' },
  { slug: 'events', name: 'События города / Афиша', icon: 'CalendarDays', description: 'Концерты, лекции, фестивали и городские мероприятия.' },
];

const NAMES = {
  'habr.com': 'Habr',
  'cnews.ru': 'CNews',
  'tadviser.ru': 'TAdviser',
  '3dnews.ru': '3DNews',
  'vc.ru': 'VC.ru',
  'roem.ru': 'Roem',
  'anti-malware.ru': 'Anti-Malware',
  'opennet.ru': 'OpenNet',
  'nixp.ru': 'NIXP',
  'xakep.ru': 'Xakep',
  'dev.by': 'Dev.by',
  'it-world.ru': 'IT-World',
  'computerra.ru': 'Компьютерра',
  'itweek.ru': 'IT Week',
  'pcmag.ru': 'PCMag.ru',
  'hi-news.ru': 'Hi-News',
  'interfax.ru': 'Интерфакс',
  'techcrunch.com': 'TechCrunch',
  'hacker-news.firebaseio.com': 'Hacker News',
  'theregister.com': 'The Register',
  'ixbt.com': 'iXBT',
  'dns-shop.ru': 'DNS',
  're.store': 're:Store',
  'settings.fm': 'Settings.fm',
  'gagadget.com': 'Gagadget',
  'mobiltelefon.ru': 'Mobiltelefon',
  'gsmarena.com': 'GSMArena',
  '4pda.to': '4PDA',
  'hi-tech.mail.ru': 'Hi-Tech Mail.ru',
  'zoom.cnews.ru': 'Zoom CNews',
  'stuff.tv': 'Stuff',
  'androidauthority.com': 'Android Authority',
  '91mobiles.com': '91mobiles',
  'notebookcheck.net': 'Notebookcheck',
  'techradar.com': 'TechRadar',
  'gizmodo.com': 'Gizmodo',
  'engadget.com': 'Engadget',
  'phonearena.com': 'PhoneArena',
  'lenta.ru': 'Lenta.ru',
  'kinopoisk.ru': 'Кинопоиск',
  'film.ru': 'Film.ru',
  'afisha.ru': 'Афиша',
  'cinemaplex.ru': 'Cinemaplex',
  'screenrant.com': 'ScreenRant',
  'kinomania.ru': 'Киномания',
  'kinobusiness.com': 'Кинобизнес',
  'totalfilm.ru': 'Total Film',
  'filmz.ru': 'Filmz',
  'kinodanz.com': 'Киноданс',
  'deadline.com': 'Deadline',
  'variety.com': 'Variety',
  'hollywoodreporter.com': 'Hollywood Reporter',
  'rottentomatoes.com': 'Rotten Tomatoes',
  'indiewire.com': 'IndieWire',
  'den-of-geek.com': 'Den of Geek',
  'slashfilm.com': '/Film',
  'empireonline.com': 'Empire',
  'rogerebert.com': 'Roger Ebert',
  'kanobu.ru': 'Канобу',
  'igromania.ru': 'Игромания',
  'stopgame.ru': 'StopGame',
  'gamemag.ru': 'GameMAG',
  'playground.ru': 'Playground',
  'ign.com': 'IGN',
  'gamespot.com': 'GameSpot',
  'pcgamer.com': 'PC Gamer',
  'rockpapershotgun.com': 'Rock Paper Shotgun',
  'kotaku.com': 'Kotaku',
  'polygon.com': 'Polygon',
  'eurogamer.net': 'Eurogamer',
  'gamesradar.com': 'GamesRadar',
  'destructoid.com': 'Destructoid',
  'vg247.com': 'VG247',
  'gamesindustry.biz': 'GamesIndustry',
  'g-mate.ru': 'G-Mate',
  'dtf.ru': 'DTF',
  '4game.com': '4Game',
  'overclockers.ru': 'Overclockers',
  'sports.ru': 'Sports.ru',
  'championat.com': 'Чемпионат',
  'sport-express.ru': 'Спорт-Экспресс',
  'football.ru': 'Football.ru',
  'sovsport.ru': 'Советский спорт',
  'futbol1.ru': 'Футбол1',
  'rsport.ria.ru': 'Р-Спорт',
  'sportbox.ru': 'Sportbox',
  'eurosport.ru': 'Eurosport',
  'goals.ru': 'Goals.ru',
  'sport24.ru': 'Sport24',
  'bombardir.ru': 'Бомбардир',
  'nhl.ru': 'NHL.ru',
  'nba.ru': 'NBA.ru',
  'tennis.ru': 'Tennis.ru',
  'voleynews.ru': 'VoleyNews',
  'wrestlingworld.ru': 'Wrestling World',
  'mmamania.com': 'MMA Mania',
  'boxnews.com.ua': 'BoxNews',
  'atletizm.com.ua': 'Atletizm',
  'rbc.ru': 'РБК',
  'vedomosti.ru': 'Ведомости',
  'kommersant.ru': 'Коммерсантъ',
  'forbes.ru': 'Forbes',
  'banki.ru': 'Банки.ру',
  'finmarket.ru': 'Финмаркет',
  'finam.ru': 'Финам',
  'investing.com': 'Investing.com',
  'tinkoff.ru': 'Т-Банк Инвестиции',
  'cbr.ru': 'Банк России',
  'smart-lab.ru': 'Smart-Lab',
  'mfd.ru': 'MFD',
  'fxssi.com': 'FXSSI',
  'bloombergquint.com': 'BQ Prime',
  'reuters.com': 'Reuters',
  'ft.com': 'Financial Times',
  'wsj.com': 'WSJ',
  'moex.com': 'Мосбиржа',
  'raiffeisen.ru': 'Райффайзен',
  'auto.ru': 'Авто.ру',
  'drive.ru': 'Драйв',
  'autoconsulting.com.ua': 'Autoconsulting',
  'motorpage.ru': 'MotorPage',
  'autonews.ru': 'Autonews',
  'zr.ru': 'За рулём',
  'autoreview.ru': 'Авторевю',
  'cars.ru': 'Cars.ru',
  'drom.ru': 'Дром',
  'avto-russia.ru': 'Авто Россия',
  'autorambler.ru': 'Авторамблер',
  'motortrend.com': 'MotorTrend',
  'caranddriver.com': 'Car and Driver',
  'topgear.com': 'Top Gear',
  'autocar.co.uk': 'Autocar',
  'jalopnik.com': 'Jalopnik',
  'carbuzz.com': 'CarBuzz',
  'autoblog.com': 'Autoblog',
  'roadandtrack.com': 'Road & Track',
  'evo.co.uk': 'Evo',
  'timeout.ru': 'Time Out',
  'rap.ru': 'Rap.ru',
  'rock-opera.ru': 'Рок-опера',
  'muzcentre.ru': 'Muzcentre',
  'pitchfork.com': 'Pitchfork',
  'nme.com': 'NME',
  'rollingstone.com': 'Rolling Stone',
  'stereogum.com': 'Stereogum',
  'spin.com': 'Spin',
  'consequence.net': 'Consequence',
  'allmusic.com': 'AllMusic',
  'musicweek.com': 'Music Week',
  'billboard.com': 'Billboard',
  'loudwire.com': 'Loudwire',
  'metalstorm.net': 'Metal Storm',
  'alternativepress.com': 'Alternative Press',
  'clashmusic.com': 'Clash',
  'thisisfakelove.com': 'This Is Fake Love',
  'resident-advisor.net': 'Resident Advisor',
  'culture.ru': 'Культура.РФ',
  'artguide.com': 'Artguide',
  'theartnewspaper.ru': 'The Art Newspaper Russia',
  'aroundart.org': 'Aroundart',
  'artchive.ru': 'Artchive',
  'designmag.ru': 'Design Mag',
  'admagazine.ru': 'AD Magazine',
  'artinfo.ru': 'Artinfo',
  'the-village.ru': 'The Village',
  'colta.ru': 'Colta',
  'artsy.net': 'Artsy',
  'artnet.com': 'Artnet',
  'frieze.com': 'Frieze',
  'apollo-magazine.com': 'Apollo',
  'hyperallergic.com': 'Hyperallergic',
  'artforum.com': 'Artforum',
  'contemporaryartdaily.com': 'Contemporary Art Daily',
  'e-flux.com': 'e-flux',
  'medportal.ru': 'Медпортал',
  'zdorovie.ru': 'Здоровье',
  'medvestnik.ru': 'Медвестник',
  'vrach.ru': 'Врач.ру',
  'consilium.medicus.ru': 'Consilium Medicum',
  'medicalxpress.com': 'Medical Xpress',
  'healthline.com': 'Healthline',
  'webmd.com': 'WebMD',
  'mayoclinic.org': 'Mayo Clinic',
  'medscape.com': 'Medscape',
  'medicalnewstoday.com': 'Medical News Today',
  'nih.gov': 'NIH',
  'sciencedaily.com': 'ScienceDaily',
  'eurekalert.org': 'EurekAlert',
  'statnews.com': 'STAT',
  'fiercehealthcare.com': 'Fierce Healthcare',
  'bmj.com': 'BMJ',
  'thelancet.com': 'The Lancet',
  'nejm.org': 'NEJM',
  'who.int': 'WHO',
  'nplus1.ru': 'N+1',
  'popmech.ru': 'Популярная механика',
  'naked-science.ru': 'Naked Science',
  'kot.sh': 'Кот Шрёдингера',
  'scientificamerican.com': 'Scientific American',
  'nature.com': 'Nature',
  'science.org': 'Science',
  'phys.org': 'Phys.org',
  'newscientist.com': 'New Scientist',
  'livescience.com': 'Live Science',
  'discovermagazine.com': 'Discover',
  'sciencenews.org': 'Science News',
  'quantamagazine.org': 'Quanta',
  'arxiv.org': 'arXiv',
  'ras.ru': 'РАН',
  'indicator.ru': 'Индикатор',
  'geographica.su': 'Geographica',
  'cosmos-journal.ru': 'Cosmos',
  'spaceweather.com': 'SpaceWeather',
  'cian.ru': 'Циан',
  'realty.rbc.ru': 'РБК Недвижимость',
  'irn.ru': 'IRN',
  'metrinfo.ru': 'Метринфо',
  'bn.ru': 'БН',
  'novostroev.ru': 'Новостроев',
  'estate.ru': 'Estate.ru',
  'domofond.ru': 'Домофонд',
  'realtor.ru': 'Realtor.ru',
  'russianrealty.ru': 'Russian Realty',
  'gdeetotdom.ru': 'ГдеЭтотДом',
  'zagorod.ru': 'Загород',
  'cottage.ru': 'Cottage.ru',
  'domania.ru': 'Домания',
  'themortgagereports.com': 'The Mortgage Reports',
  'inman.com': 'Inman',
  'realtor.com': 'Realtor.com',
  'housingwire.com': 'HousingWire',
  'bloomberg.com': 'Bloomberg',
  'tourprom.ru': 'Турпром',
  'turizm.ru': 'Туризм.ру',
  'turstat.com': 'Турстат',
  'tonkosti.ru': 'Тонкости',
  'travel.ru': 'Travel.ru',
  'tutu.ru': 'Туту',
  'aviasales.ru': 'Aviasales',
  'travelask.ru': 'TravelAsk',
  'geografua.com': 'Geografua',
  'nat-geo.ru': 'Nat Geo',
  'tripadvisor.ru': 'Tripadvisor',
  'wanderlust.co.uk': 'Wanderlust',
  'lonelyplanet.com': 'Lonely Planet',
  'travelandleisure.com': 'Travel + Leisure',
  'cntraveler.com': 'Condé Nast Traveler',
  'roughguides.com': 'Rough Guides',
  'frommers.com': 'Frommer\'s',
  'afar.com': 'AFAR',
  'atlasobscura.com': 'Atlas Obscura',
  'timeout.com': 'Time Out',
  'elle.ru': 'Elle',
  'vogue.ru': 'Vogue',
  'cosmo.ru': 'Cosmo',
  'instyle.ru': 'InStyle',
  'harpersbazaar.ru': 'Harper\'s Bazaar',
  'buro247.ru': 'BURO',
  'thelocals.ru': 'The Locals',
  'wonderzine.com': 'Wonderzine',
  'snob.ru': 'Сноб',
  'peopletalk.ru': 'Peopletalk',
  'fashionista.com': 'Fashionista',
  'wwd.com': 'WWD',
  'businessoffashion.com': 'BoF',
  'hypebeast.com': 'Hypebeast',
  'highsnobiety.com': 'Highsnobiety',
  'fashionunited.com': 'FashionUnited',
  'dazeddigital.com': 'Dazed',
  'nymag.com': 'New York Magazine',
  'refinery29.com': 'Refinery29',
  'thecut.com': 'The Cut',
  'coindesk.com': 'CoinDesk',
  'cointelegraph.com': 'Cointelegraph',
  'decrypt.co': 'Decrypt',
  'cryptonews.com': 'CryptoNews',
  'cryptopanic.com': 'CryptoPanic',
  'beincrypto.com': 'BeInCrypto',
  'bitcoinmagazine.com': 'Bitcoin Magazine',
  'cryptoslate.com': 'CryptoSlate',
  'theblock.co': 'The Block',
  'ambcrypto.com': 'AMBCrypto',
  'coingape.com': 'CoinGape',
  'u.today': 'U.Today',
  'bitcoinist.com': 'Bitcoinist',
  'dailyhodl.com': 'DailyHodl',
  'trustnodes.com': 'Trustnodes',
  'crypto.ru': 'Crypto.ru',
  'bitnovosti.com': 'BitNovosti',
  'forklog.com': 'ForkLog',
  'coinspot.io': 'Coinspot',
  'cryptorank.io': 'CryptoRank',
  'tass.ru': 'ТАСС',
  'ria.ru': 'РИА Новости',
  'iz.ru': 'Известия',
  'mk.ru': 'МК',
  'gazeta.ru': 'Газета.ру',
  'ng.ru': 'Независимая газета',
  'theins.ru': 'The Insider',
  'meduza.io': 'Meduza',
  'novayagazeta.ru': 'Новая газета',
  'bbc.com': 'BBC Russian',
  'apnews.com': 'AP',
  'theguardian.com': 'The Guardian',
  'nytimes.com': 'NYT',
  'foreignpolicy.com': 'Foreign Policy',
  'politico.com': 'Politico',
  'restoclub.ru': 'Restoclub',
  'gastronom.ru': 'Гастрономъ',
  'eda.ru': 'Еда.ру',
  'gotovim.ru': 'Готовим.ру',
  'povarenok.ru': 'Поварёнок',
  'food52.com': 'Food52',
  'eater.com': 'Eater',
  'seriouseats.com': 'Serious Eats',
  'bonappetit.com': 'Bon Appétit',
  'epicurious.com': 'Epicurious',
  'saveur.com': 'Saveur',
  'thekitchn.com': 'The Kitchn',
  'chowhound.com': 'Chowhound',
  'finedininglovers.com': 'Fine Dining Lovers',
  'michelin.com': 'Michelin',
  'zagat.com': 'Zagat',
  'infood.ru': 'InFood',
  'kudago.com': 'KudaGo',
  'timepad.ru': 'Timepad',
  'peterburg.ru': 'Петербург.ру',
  'kudamoscow.ru': 'КудаМосква',
  'kassir.ru': 'Кассир.ру',
  'ponominalu.ru': 'Яндекс Афиша',
  'ticketland.ru': 'Ticketland',
  'eventbrite.ru': 'Eventbrite',
  'bileter.ru': 'Билетер',
  'rambler.ru': 'Рамблер Афиша',
  'afisha-yekaterinburg.ru': 'Афиша Екатеринбург',
  'afisha-nsk.ru': 'Афиша Новосибирск',
  'bilety.ru': 'Билеты.ру',
  'concert.ru': 'Concert.ru',
  'ticketscloud.com': 'Ticketscloud',
  'all-events.ru': 'All-Events',
  'afisha-kazan.ru': 'Афиша Казань',
};

function hostKey(path) {
  return path.replace(/^https?:\/\//, '').replace(/^www\./, '').split('/')[0];
}

function displayName(path) {
  return NAMES[hostKey(path)] || hostKey(path);
}

function toUrl(path) {
  return path.startsWith('http') ? path : `https://${path}`;
}

function rss(topic, path, rssUrl, extra = {}) {
  return {
    name: displayName(path),
    url: toUrl(path),
    type: 'rss',
    topic,
    city: extra.city || null,
    parser_config: { rss_url: rssUrl, is_event: Boolean(extra.event) },
  };
}

function html(topic, path, extra = {}) {
  return {
    name: displayName(path),
    url: toUrl(path),
    type: 'html',
    topic,
    city: extra.city || null,
    parser_config: {
      list_url: toUrl(path),
      is_event: Boolean(extra.event),
      selectors: DEFAULT_HTML_SELECTORS,
    },
  };
}

function api(topic, path, parser_config, extra = {}) {
  return {
    name: displayName(path),
    url: toUrl(path),
    type: 'api',
    topic,
    city: extra.city || null,
    parser_config,
  };
}

export const ALL_SOURCES = [
  rss('it', 'habr.com', 'https://habr.com/ru/rss/articles/'),
  rss('it', 'cnews.ru', 'https://www.cnews.ru/inc/rss/news.xml'),
  html('it', 'tadviser.ru'),
  rss('it', '3dnews.ru', 'https://3dnews.ru/news/rss/'),
  rss('it', 'vc.ru', 'https://vc.ru/rss'),
  rss('it', 'roem.ru', 'https://roem.ru/rss/index.xml'),
  html('it', 'anti-malware.ru'),
  rss('it', 'opennet.ru', 'https://www.opennet.ru/opennews/opennews_all.rss'),
  html('it', 'nixp.ru'),
  rss('it', 'xakep.ru', 'https://xakep.ru/feed/'),
  rss('it', 'dev.by', 'https://devby.io/rss'),
  html('it', 'it-world.ru'),
  rss('it', 'computerra.ru', 'https://computerra.ru/feed/'),
  html('it', 'itweek.ru'),
  html('it', 'pcmag.ru'),
  rss('it', 'hi-news.ru', 'https://hi-news.ru/feed'),
  rss('it', 'interfax.ru/tag/it', 'https://www.interfax.ru/rss.asp'),
  rss('it', 'techcrunch.com', 'https://techcrunch.com/feed/'),
  api('it', 'hacker-news.firebaseio.com', { provider: 'hackernews' }),
  rss('it', 'theregister.com', 'https://www.theregister.com/headlines.rss'),

  rss('electronics', 'ixbt.com', 'https://www.ixbt.com/export/news.rss'),
  rss('electronics', '3dnews.ru', 'https://3dnews.ru/news/rss/'),
  html('electronics', 'dns-shop.ru/blog'),
  html('electronics', 're.store/blog'),
  html('electronics', 'settings.fm'),
  rss('electronics', 'gagadget.com', 'https://gagadget.com/feed/'),
  html('electronics', 'mobiltelefon.ru'),
  rss('electronics', 'gsmarena.com', 'https://www.gsmarena.com/rss-news-reviews.php3'),
  rss('electronics', '4pda.to', 'https://4pda.to/feed/'),
  rss('electronics', 'hi-tech.mail.ru', 'https://hi-tech.mail.ru/rss/all/'),
  html('electronics', 'zoom.cnews.ru'),
  rss('electronics', 'stuff.tv', 'https://www.stuff.tv/feed/'),
  rss('electronics', 'androidauthority.com', 'https://www.androidauthority.com/feed/'),
  rss('electronics', '91mobiles.com', 'https://www.91mobiles.com/hub/feed/'),
  rss('electronics', 'notebookcheck.net', 'https://www.notebookcheck.net/RSS.1175.0.html'),
  rss('electronics', 'techradar.com', 'https://www.techradar.com/rss'),
  rss('electronics', 'gizmodo.com', 'https://gizmodo.com/rss'),
  rss('electronics', 'engadget.com', 'https://www.engadget.com/rss.xml'),
  rss('electronics', 'phonearena.com', 'https://www.phonearena.com/feed'),
  rss('electronics', 'lenta.ru/rubrics/science/technology', 'https://lenta.ru/rss/news/science/'),

  html('cinema', 'kinopoisk.ru/media'),
  rss('cinema', 'film.ru', 'https://www.film.ru/rss.xml'),
  html('cinema', 'afisha.ru/movies', { event: true }),
  html('cinema', 'cinemaplex.ru'),
  rss('cinema', 'screenrant.com', 'https://screenrant.com/feed/'),
  html('cinema', 'kinomania.ru'),
  html('cinema', 'kinobusiness.com'),
  html('cinema', 'totalfilm.ru'),
  html('cinema', 'filmz.ru'),
  html('cinema', 'kinodanz.com'),
  rss('cinema', 'deadline.com', 'https://deadline.com/feed/'),
  rss('cinema', 'variety.com', 'https://variety.com/feed/'),
  rss('cinema', 'hollywoodreporter.com', 'https://www.hollywoodreporter.com/feed/'),
  html('cinema', 'rottentomatoes.com/news'),
  rss('cinema', 'indiewire.com', 'https://www.indiewire.com/feed/'),
  rss('cinema', 'den-of-geek.com', 'https://www.denofgeek.com/feed/'),
  rss('cinema', 'slashfilm.com', 'https://www.slashfilm.com/feed/'),
  rss('cinema', 'empireonline.com', 'https://www.empireonline.com/rss.xml'),
  rss('cinema', 'rogerebert.com', 'https://www.rogerebert.com/feed'),
  html('cinema', 'kanobu.ru'),

  rss('games', 'igromania.ru', 'https://www.igromania.ru/rss.xml'),
  html('games', 'stopgame.ru'),
  html('games', 'kanobu.ru'),
  html('games', 'gamemag.ru'),
  html('games', 'playground.ru'),
  rss('games', 'ign.com', 'https://feeds.feedburner.com/ign/all'),
  rss('games', 'gamespot.com', 'https://www.gamespot.com/feeds/mashup/'),
  rss('games', 'pcgamer.com', 'https://www.pcgamer.com/rss/'),
  rss('games', 'rockpapershotgun.com', 'https://www.rockpapershotgun.com/feed'),
  rss('games', 'kotaku.com', 'https://kotaku.com/rss'),
  rss('games', 'polygon.com', 'https://www.polygon.com/rss/index.xml'),
  rss('games', 'eurogamer.net', 'https://www.eurogamer.net/feed'),
  rss('games', 'gamesradar.com', 'https://www.gamesradar.com/rss/'),
  rss('games', 'destructoid.com', 'https://www.destructoid.com/feed/'),
  rss('games', 'vg247.com', 'https://www.vg247.com/feed/'),
  rss('games', 'gamesindustry.biz', 'https://www.gamesindustry.biz/feed'),
  html('games', 'g-mate.ru'),
  rss('games', 'dtf.ru/games', 'https://dtf.ru/rss/games'),
  html('games', '4game.com/news'),
  html('games', 'overclockers.ru/games'),

  rss('sport', 'sports.ru', 'https://www.sports.ru/rss/all_news.xml'),
  rss('sport', 'championat.com', 'https://www.championat.com/rss/news.html'),
  html('sport', 'sport-express.ru'),
  html('sport', 'football.ru'),
  html('sport', 'sovsport.ru'),
  html('sport', 'futbol1.ru'),
  rss('sport', 'rsport.ria.ru', 'https://rsport.ria.ru/export/rss2/archive/index.xml'),
  html('sport', 'sportbox.ru'),
  html('sport', 'eurosport.ru'),
  html('sport', 'goals.ru'),
  html('sport', 'sport24.ru'),
  html('sport', 'bombardir.ru'),
  html('sport', 'nhl.ru'),
  html('sport', 'nba.ru'),
  html('sport', 'tennis.ru'),
  html('sport', 'voleynews.ru'),
  html('sport', 'wrestlingworld.ru'),
  rss('sport', 'mmamania.com', 'https://www.mmamania.com/rss/index.xml'),
  html('sport', 'boxnews.com.ua'),
  html('sport', 'atletizm.com.ua'),

  rss('finance', 'rbc.ru', 'https://rssexport.rbc.ru/rbcnews/news/30/full.rss'),
  rss('finance', 'vedomosti.ru', 'https://www.vedomosti.ru/rss/news'),
  rss('finance', 'kommersant.ru', 'https://www.kommersant.ru/RSS/news.xml'),
  rss('finance', 'forbes.ru', 'https://www.forbes.ru/newrss.xml'),
  rss('finance', 'banki.ru', 'https://www.banki.ru/xml/news.rss'),
  html('finance', 'finmarket.ru'),
  html('finance', 'finam.ru'),
  html('finance', 'investing.com/news/russia'),
  html('finance', 'tinkoff.ru/invest/news'),
  rss('finance', 'interfax.ru/finances', 'https://www.interfax.ru/rss.asp'),
  html('finance', 'cbr.ru/press'),
  html('finance', 'smart-lab.ru'),
  html('finance', 'mfd.ru'),
  html('finance', 'fxssi.com'),
  html('finance', 'bloombergquint.com'),
  rss('finance', 'reuters.com/finance', 'https://www.reutersagency.com/feed/?best-topics=business-finance&post_type=best'),
  html('finance', 'ft.com'),
  html('finance', 'wsj.com'),
  html('finance', 'moex.com/news'),
  html('finance', 'raiffeisen.ru/news'),

  html('auto', 'auto.ru/magazine'),
  html('auto', 'drive.ru'),
  html('auto', 'autoconsulting.com.ua'),
  html('auto', 'motorpage.ru'),
  html('auto', 'autonews.ru'),
  html('auto', 'zr.ru'),
  html('auto', 'autoreview.ru'),
  html('auto', 'cars.ru'),
  html('auto', 'drom.ru/info/misc'),
  html('auto', 'avto-russia.ru'),
  html('auto', 'autorambler.ru'),
  rss('auto', 'motortrend.com', 'https://www.motortrend.com/feed/'),
  rss('auto', 'caranddriver.com', 'https://www.caranddriver.com/rss/all.xml/'),
  rss('auto', 'topgear.com', 'https://www.topgear.com/rss.xml'),
  rss('auto', 'autocar.co.uk', 'https://www.autocar.co.uk/rss'),
  rss('auto', 'jalopnik.com', 'https://jalopnik.com/rss'),
  rss('auto', 'carbuzz.com', 'https://carbuzz.com/feed/'),
  rss('auto', 'autoblog.com', 'https://www.autoblog.com/rss.xml'),
  rss('auto', 'roadandtrack.com', 'https://www.roadandtrack.com/rss/all.xml/'),
  rss('auto', 'evo.co.uk', 'https://www.evo.co.uk/feeds/all'),

  html('music', 'afisha.ru/concerts', { event: true }),
  html('music', 'timeout.ru/music', { event: true }),
  html('music', 'rap.ru'),
  html('music', 'rock-opera.ru'),
  html('music', 'muzcentre.ru'),
  rss('music', 'intermedia.ru', 'https://www.intermedia.ru/rss/news.xml'),
  api('music', 'kudago.com', { provider: 'kudago', categories: 'concert' }),

  html('art', 'culture.ru'),
  html('art', 'afisha.ru/exhibitions', { event: true }),
  html('art', 'artguide.com'),
  html('art', 'theartnewspaper.ru'),
  html('art', 'aroundart.org'),
  html('art', 'artchive.ru'),
  html('art', 'designmag.ru'),
  html('art', 'admagazine.ru'),
  html('art', 'artinfo.ru'),
  html('art', 'the-village.ru/city/culture'),
  html('art', 'colta.ru'),
  html('art', 'timeout.ru/arts'),
  rss('art', 'artsy.net', 'https://www.artsy.net/rss/news'),
  rss('art', 'artnet.com', 'https://news.artnet.com/feed'),
  rss('art', 'frieze.com', 'https://www.frieze.com/feed/rss'),
  rss('art', 'apollo-magazine.com', 'https://www.apollo-magazine.com/feed/'),
  rss('art', 'hyperallergic.com', 'https://hyperallergic.com/feed/'),
  rss('art', 'artforum.com', 'https://www.artforum.com/feed/'),
  html('art', 'contemporaryartdaily.com'),
  rss('art', 'e-flux.com', 'https://www.e-flux.com/rss/'),
  api('art', 'kudago.com', { provider: 'kudago', categories: 'exhibition' }),

  html('health', 'medportal.ru'),
  html('health', 'zdorovie.ru'),
  html('health', 'medvestnik.ru'),
  html('health', 'vrach.ru'),
  html('health', 'consilium.medicus.ru'),
  rss('health', 'medicalxpress.com', 'https://medicalxpress.com/rss-feed/'),
  rss('health', 'healthline.com', 'https://www.healthline.com/rss/health-news'),
  html('health', 'webmd.com'),
  html('health', 'mayoclinic.org/news'),
  html('health', 'medscape.com'),
  rss('health', 'medicalnewstoday.com', 'https://www.medicalnewstoday.com/rss'),
  rss('health', 'nih.gov/news', 'https://www.nih.gov/news-events/news-releases/feed.xml'),
  rss('health', 'sciencedaily.com/health', 'https://www.sciencedaily.com/rss/health_medicine.xml'),
  html('health', 'eurekalert.org/health'),
  rss('health', 'statnews.com', 'https://www.statnews.com/feed/'),
  rss('health', 'fiercehealthcare.com', 'https://www.fiercehealthcare.com/rss/xml'),
  html('health', 'bmj.com/news'),
  html('health', 'thelancet.com/news'),
  html('health', 'nejm.org/news'),
  rss('health', 'who.int/news', 'https://www.who.int/rss-feeds/news-english.xml'),

  rss('science', 'nplus1.ru', 'https://nplus1.ru/rss'),
  rss('science', 'popmech.ru', 'https://www.popmech.ru/out/public-all.xml'),
  rss('science', 'naked-science.ru', 'https://naked-science.ru/feed'),
  html('science', 'kot.sh'),
  rss('science', 'scientificamerican.com', 'https://www.scientificamerican.com/feed/'),
  rss('science', 'nature.com/news', 'https://www.nature.com/nature.rss'),
  rss('science', 'science.org/news', 'https://www.science.org/rss/news_current.xml'),
  rss('science', 'phys.org', 'https://phys.org/rss-feed/'),
  rss('science', 'sciencedaily.com', 'https://www.sciencedaily.com/rss/all.xml'),
  rss('science', 'newscientist.com', 'https://www.newscientist.com/feed/home/'),
  rss('science', 'livescience.com', 'https://www.livescience.com/feeds/all'),
  rss('science', 'discovermagazine.com', 'https://www.discovermagazine.com/rss'),
  rss('science', 'sciencenews.org', 'https://www.sciencenews.org/feed'),
  rss('science', 'quantamagazine.org', 'https://www.quantamagazine.org/feed/'),
  api('science', 'arxiv.org', { provider: 'arxiv' }),
  html('science', 'ras.ru/news'),
  html('science', 'indicator.ru'),
  html('science', 'geographica.su'),
  html('science', 'cosmos-journal.ru'),
  rss('science', 'spaceweather.com', 'https://www.spaceweather.com/swrss.xml'),

  html('realty', 'cian.ru/stati'),
  html('realty', 'realty.rbc.ru'),
  html('realty', 'irn.ru'),
  html('realty', 'metrinfo.ru'),
  html('realty', 'bn.ru/news'),
  html('realty', 'novostroev.ru'),
  html('realty', 'estate.ru'),
  html('realty', 'domofond.ru/news'),
  html('realty', 'realtor.ru/news'),
  html('realty', 'russianrealty.ru'),
  html('realty', 'gdeetotdom.ru/news'),
  html('realty', 'zagorod.ru/news'),
  html('realty', 'cottage.ru/news'),
  html('realty', 'domania.ru'),
  rss('realty', 'themortgagereports.com', 'https://themortgagereports.com/feed'),
  rss('realty', 'inman.com', 'https://www.inman.com/feed/'),
  rss('realty', 'realtor.com/news', 'https://www.realtor.com/news/feed/'),
  rss('realty', 'housingwire.com', 'https://www.housingwire.com/feed/'),
  html('realty', 'bloomberg.com/real-estate'),

  html('travel', 'tourprom.ru'),
  html('travel', 'turizm.ru'),
  html('travel', 'turstat.com'),
  html('travel', 'tonkosti.ru'),
  html('travel', 'travel.ru'),
  html('travel', 'tutu.ru/journal'),
  html('travel', 'aviasales.ru/blog'),
  html('travel', 'travelask.ru'),
  html('travel', 'geografua.com'),
  html('travel', 'nat-geo.ru/travel'),
  html('travel', 'tripadvisor.ru/travel'),
  rss('travel', 'wanderlust.co.uk', 'https://www.wanderlust.co.uk/feed/'),
  rss('travel', 'lonelyplanet.com/news', 'https://www.lonelyplanet.com/feed/news'),
  rss('travel', 'travelandleisure.com', 'https://www.travelandleisure.com/rss'),
  rss('travel', 'cntraveler.com', 'https://www.cntraveler.com/feed/rss'),
  rss('travel', 'roughguides.com/article', 'https://www.roughguides.com/feed/'),
  html('travel', 'frommers.com/news'),
  rss('travel', 'afar.com', 'https://www.afar.com/rss.xml'),
  rss('travel', 'atlasobscura.com', 'https://www.atlasobscura.com/feeds/latest'),
  rss('travel', 'timeout.com/travel', 'https://www.timeout.com/feed'),

  html('fashion', 'elle.ru'),
  html('fashion', 'vogue.ru'),
  html('fashion', 'cosmo.ru'),
  html('fashion', 'instyle.ru'),
  html('fashion', 'harpersbazaar.ru'),
  html('fashion', 'buro247.ru'),
  html('fashion', 'thelocals.ru'),
  html('fashion', 'wonderzine.com'),
  html('fashion', 'snob.ru/style'),
  html('fashion', 'peopletalk.ru/style'),
  rss('fashion', 'fashionista.com', 'https://fashionista.com/feed'),
  rss('fashion', 'wwd.com', 'https://wwd.com/feed/'),
  rss('fashion', 'businessoffashion.com', 'https://www.businessoffashion.com/feed/'),
  rss('fashion', 'hypebeast.com', 'https://hypebeast.com/feed'),
  rss('fashion', 'highsnobiety.com', 'https://www.highsnobiety.com/rss'),
  rss('fashion', 'fashionunited.com', 'https://fashionunited.com/rss'),
  rss('fashion', 'dazeddigital.com', 'https://www.dazeddigital.com/rss'),
  rss('fashion', 'nymag.com/fashion', 'https://nymag.com/rss.xml'),
  rss('fashion', 'refinery29.com/fashion', 'https://www.refinery29.com/fashion/rss.xml'),
  rss('fashion', 'thecut.com', 'https://www.thecut.com/rss.xml'),

  rss('crypto', 'coindesk.com', 'https://www.coindesk.com/arc/outboundfeeds/rss/'),
  rss('crypto', 'cointelegraph.com', 'https://cointelegraph.com/rss'),
  rss('crypto', 'decrypt.co', 'https://decrypt.co/feed'),
  rss('crypto', 'cryptonews.com', 'https://cryptonews.com/news/feed/'),
  html('crypto', 'cryptopanic.com'),
  rss('crypto', 'beincrypto.com', 'https://beincrypto.com/feed/'),
  rss('crypto', 'bitcoinmagazine.com', 'https://bitcoinmagazine.com/.rss/full/'),
  rss('crypto', 'cryptoslate.com', 'https://cryptoslate.com/feed/'),
  html('crypto', 'theblock.co'),
  rss('crypto', 'ambcrypto.com', 'https://ambcrypto.com/feed/'),
  rss('crypto', 'coingape.com', 'https://coingape.com/feed/'),
  rss('crypto', 'u.today', 'https://u.today/rss'),
  rss('crypto', 'bitcoinist.com', 'https://bitcoinist.com/feed/'),
  rss('crypto', 'dailyhodl.com', 'https://dailyhodl.com/feed/'),
  rss('crypto', 'trustnodes.com', 'https://www.trustnodes.com/feed'),
  html('crypto', 'crypto.ru'),
  html('crypto', 'bitnovosti.com'),
  rss('crypto', 'forklog.com', 'https://forklog.com/feed/'),
  html('crypto', 'coinspot.io'),
  html('crypto', 'cryptorank.io/news'),

  rss('politics', 'rbc.ru', 'https://rssexport.rbc.ru/rbcnews/news/30/full.rss'),
  rss('politics', 'interfax.ru', 'https://www.interfax.ru/rss.asp'),
  rss('politics', 'tass.ru', 'https://tass.ru/rss/v2.xml'),
  rss('politics', 'ria.ru', 'https://ria.ru/export/rss2/archive/index.xml'),
  rss('politics', 'lenta.ru', 'https://lenta.ru/rss/news'),
  rss('politics', 'iz.ru', 'https://iz.ru/xml/rss/all.xml'),
  rss('politics', 'mk.ru', 'https://www.mk.ru/rss/index.xml'),
  rss('politics', 'gazeta.ru', 'https://www.gazeta.ru/export/rss/lenta.xml'),
  html('politics', 'ng.ru'),
  rss('politics', 'kommersant.ru', 'https://www.kommersant.ru/RSS/news.xml'),
  html('politics', 'theins.ru'),
  rss('politics', 'meduza.io', 'https://meduza.io/rss/all'),
  html('politics', 'novayagazeta.ru'),
  rss('politics', 'bbc.com/russian', 'https://feeds.bbci.co.uk/russian/rss.xml'),
  rss('politics', 'reuters.com', 'https://www.reutersagency.com/feed/?best-topics=political-general&post_type=best'),
  html('politics', 'apnews.com'),
  rss('politics', 'theguardian.com', 'https://www.theguardian.com/world/rss'),
  rss('politics', 'nytimes.com', 'https://rss.nytimes.com/services/xml/rss/nyt/World.xml'),
  rss('politics', 'foreignpolicy.com', 'https://foreignpolicy.com/feed/'),
  rss('politics', 'politico.com', 'https://www.politico.com/rss/politics08.xml'),

  html('food', 'afisha.ru/restaurants'),
  html('food', 'restoclub.ru'),
  html('food', 'timeout.ru/food'),
  html('food', 'the-village.ru/food'),
  html('food', 'gastronom.ru'),
  html('food', 'eda.ru/media'),
  html('food', 'gotovim.ru'),
  html('food', 'povarenok.ru/news'),
  rss('food', 'food52.com', 'https://food52.com/blog.rss'),
  rss('food', 'eater.com', 'https://www.eater.com/rss/index.xml'),
  rss('food', 'seriouseats.com', 'https://www.seriouseats.com/rss'),
  rss('food', 'bonappetit.com', 'https://www.bonappetit.com/feed/rss'),
  rss('food', 'epicurious.com', 'https://www.epicurious.com/feed/rss'),
  rss('food', 'saveur.com', 'https://www.saveur.com/feed/'),
  rss('food', 'thekitchn.com', 'https://www.thekitchn.com/feed'),
  html('food', 'chowhound.com'),
  rss('food', 'finedininglovers.com', 'https://www.finedininglovers.com/rss.xml'),
  html('food', 'michelin.com/news'),
  html('food', 'zagat.com'),
  html('food', 'infood.ru'),
  api('food', 'kudago.com', { provider: 'kudago', categories: 'festival' }),

  html('events', 'afisha.ru', { event: true }),
  api('events', 'kudago.com', { provider: 'kudago' }),
  html('events', 'timeout.ru', { event: true }),
  html('events', 'timepad.ru', { event: true }),
  html('events', 'peterburg.ru/events', { city: 'spb', event: true }),
  html('events', 'kudamoscow.ru', { city: 'moscow', event: true }),
  html('events', 'culture.ru/events', { event: true }),
  html('events', 'kassir.ru', { event: true }),
  html('events', 'ponominalu.ru', { event: true }),
  html('events', 'ticketland.ru', { event: true }),
  html('events', 'eventbrite.ru', { event: true }),
  html('events', 'bileter.ru', { event: true }),
  html('events', 'rambler.ru/afisha', { event: true }),
  html('events', 'afisha-yekaterinburg.ru', { city: 'ekb', event: true }),
  html('events', 'afisha-nsk.ru', { city: 'nsk', event: true }),
  html('events', 'bilety.ru', { event: true }),
  html('events', 'concert.ru', { event: true }),
  html('events', 'ticketscloud.com', { event: true }),
  html('events', 'all-events.ru', { event: true }),
  html('events', 'afisha-kazan.ru', { city: 'kazan', event: true }),
];

export const SOURCES = ALL_SOURCES.filter((source) => isRussianSource(source.url));
